<div id="left">
	  <ul>
	    <li class="menu"><a href="#"><img src="../images/leftbutton/left1.png"/></a>
	      <ul class="submenu" id="memu1">
	        <li><a href=""><img src="../images/leftbutton/ls1.png"/></a></li>
	        <li><a href=""><img src="../images/leftbutton/ls2.png"/></a></li>
	        <li><a href=""><img src="../images/leftbutton/ls3.png"/></a></li>
	        <li><a href=""><img src="../images/leftbutton/ls4.png"/></a></li>
	      </ul>
	    </li>
	    <li class="menu"><a href="#"><img src="../images/leftbutton/left1.png"/></a>
	      <ul class="submenu" id="memu1">
	        <li><a href=""><img src="../images/leftbutton/ls1.png"/></a></li>
	        <li><a href=""><img src="../images/leftbutton/ls1.png"/></a></li>
	        <li><a href=""><img src="../images/leftbutton/ls3.png"/></a></li>
	        <li><a href=""><img src="../images/leftbutton/ls4.png"/></a></li>
	      </ul>
	    </li>

	  </ul>
	</div>